# основные настройки и правила gateway находятся в configserver

server:
  port: 8088


logging:
  level:
    root: DEBUG

spring:
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    config:
      # не загружать другие компоненты до получения конфигурации
      fail-fast: true
      # если config-server недоступен, нужно сделать несколько попыток подключиться
      retry:
        # используем случайный backoff между попытками
        useRandomPolicy: true
        # максимальный интервал, в течение которого делаем попытки (6000 миллисекунд = 6 сек)
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/


