services:

  first-service:
    container_name: first-service
    build: ./service/first-service
    ports:
      - 8080:8080
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  keycloak_postgres:
    image: postgres:16
    container_name: keycloak_postgres
    env_file:
      - keycloak.env
    volumes:
      - ./keycloak_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_server
    env_file:
      - keycloak.env
    volumes:
      - ./keycloak-themes:/opt/keycloak/themes
    ports:
      - "8080:8080"
      - "5005:5005" # только отладки
      - "9000:9000" # панель администратора
    command:
      - start-dev # исправить на start для боевой среды
    depends_on:
      - keycloak_postgres

volumes:
  keycloak_data:


networks:
  default:
    name: microservices-network