apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-service
  namespace: my-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-service
  template:
    metadata:
      labels:
        app: second-service
    spec:
      containers:
      - name: second-service
        image: second-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: "1024Mi"  # Максимальный объем памяти
            cpu: "1"          # Максимальное количество CPU (1 ядро)
          requests:
            memory: "512Mi"   # Запрашиваемый объем памяти
            cpu: "0.5"        # Запрашиваемое количество CPU (половина ядра)
        envFrom:
          - configMapRef:
              name: microservice-cfg
          - secretRef:
              name: db-secrets