apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: my-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: discovery-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: "1024Mi"  # Максимальный объем памяти
            cpu: "1"          # Максимальное количество CPU (1 ядро)
          requests:
            memory: "512Mi"   # Запрашиваемый объем памяти
            cpu: "0.5"        # Запрашиваемое количество CPU (половина ядра)
