apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-endpoints-binding
  namespace: my-microservice
subjects:
  - kind: ServiceAccount
    name: default
    namespace: my-microservice
roleRef:
  kind: Role
  name: read-endpoints-role
  apiGroup: rbac.authorization.k8s.io