apiVersion: v1
kind: Service
metadata:
  name: consul-server
spec:
  selector:
    app: consul-server
  ports:
    - name: http
      protocol: TCP
      port: 8500
      targetPort: 8500
      
    - name: dns
      protocol: UDP
      port: 8600
      targetPort: 8600