server:
  port: 8080

spring:
  cloud:
    gateway:
      # Настройка автоматического обнаружения сервисов
      discovery:
        locator:
          enabled: true

      # Настройка глобальных фильтров (применяются ко всем маршрутам)
      # default-filters:
      #   - RequestRateLimiter=route,5 # ограничение по кликам (требует включения библиотек в pom файле) или можно через Resilience4j

      routes:
        - id: first_service_route
          uri: lb://first-service
          predicates:
            - Path=/first-service/**
          filters:
            - StripPrefix=1

        - id: second_service_route
          # Префикс lb активирует балансировщика нагрузки, учитывая адреса сервисов из DiscoveryClient
          uri: lb://second-service
          predicates:
            - Path=/second-service/**
            # - After=2024-09-01T00:00:00.000-03:00[Europe/Moscow]  # Предикат времени
            # - Before=3025-09-01T00:00:00.000-03:00[Europe/Moscow] # Предикат времени
            # - Header=X-Requested-With,.*XMLHttpRequest  # Дополнительный предикат
            # - Cookie=sessionId,abc.*  # Проверка cookie
          filters:
            - PrefixPath=/api/v1 # фильтр добавляет в начало пути префикс /api/v1
            # Ещё стоит поискать GatewayFilter Factories в документации:
            # https://cloud.spring.io/spring-cloud-gateway/reference/html/#gatewayfilter-factories
            # - CircuitBreaker=myCircuitBreaker  # Защита от отказов
            # - RequestRateLimiter=remoteaddr,5  # Ограничение частоты запросов
            # - LocalResponseCache=10m,100MB  # Кеширование ответов
            # - Hystrix=commandName  # Дополнительные возможности отказоустойчивости
            # - Retry=3  # Повторные попытки
            # - AddResponseHeader=X-Order-Category,Custom  # Добавление заголовка
            # - StripPrefix=1  # Удаление префикса из пути
            # - RewritePath=/third-service/(?<segment>.*), /$$\{segment}  # Переписывание пути
            # - AddRequestHeader=X-Special-Header,Value  # Добавление заголовка запроса
            # - RemoveRequestHeader=Authorization  # Удаление заголовка
            # - SetPath=/new-path  # Установка нового пути
            # - RemoveResponseHeader=Server  # Удаление заголовка ответа
