apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: my-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: config-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            memory: "1024Mi"  # Максимальный объем памяти
            cpu: "1"          # Максимальное количество CPU (1 ядро)
          requests:
            memory: "512Mi"   # Запрашиваемый объем памяти
            cpu: "0.5"        # Запрашиваемое количество CPU (половина ядра)
        env:
          - name: DISCOVERY_SERVER_URL
            value: http://discovery-server:8761/eureka/