server:
  port: ${SERVER_PORT:8082} # ноль - случайный пустой порт

spring:
  application:
    name: second-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      discovery:
        enabled: false # отключаем по причине, указанной в README
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:"http://localhost:8888/eureka/"}
