spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: first-service
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
