server:
  port: 8080 # ноль - случайный пустой порт

spring:
  application:
    name: first-service

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      schema: classpath:schema.sql
      data: classpath:data.sql

management:
  endpoints:
    web:
      exposure:
        include: "*"