server:
  port: 8081

spring:
  application:
    name: first-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # указание этого избавляет от создания бина JwtDecoder
          issuer-uri: http://localhost:8080/realms/my-realm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/my-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-security
            client-secret: 9mqPlu7tzhtZItGLwg3eBQi3r7hyGGl1
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - roles

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      springframework.security: INFO

