server:
  port: 8081

# Настройки Kafka
spring:
  application:
    name: kafka-consumers
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1 # количество потоков прослушки
    consumer:
      base-name: Consumer
      topic: kafka-demo-1
      number-of-consumers: 1
      enable-auto-commit: true
      client-id: consumers-demo
      group-id: consumers-group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.alexgur.kafka.deserializer.UserDeserializer