apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.ingressName }}
  namespace: {{.Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.annotations.rewriteTarget }}
    nginx.ingress.kubernetes.io/use-regex: "{{ .Values.annotations.useRegex }}"
spec:
  ingressClassName: {{.Values.ingressClassName }}
  rules:
    - http:
        paths:
{{- range .Values.paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .port }}
{{- end }}
